apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: orchestrator
  namespace: default
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: ghost-engine
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/orchestrator:latest
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
          resources:
            limits:
              cpu: 1
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 3
            periodSeconds: 30
